//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistics
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loading_Railway
    {
        public int id_Loading_Railway { get; set; }
        public int Capacity { get; set; }
        public int id_Station_Loading { get; set; }
        public int id_Storage { get; set; }
        public int id_user { get; set; }
        public System.DateTime Date { get; set; }
        public int id_Railway { get; set; }
    
        public virtual Railway Railway { get; set; }
        public virtual Station_Loading Station_Loading { get; set; }
        public virtual Storage_Accounting Storage_Accounting { get; set; }
        public virtual User User { get; set; }
    }
}
